### ISSUE TITLE
 This entity is not allowed by currently active license!

### ISSUE THREAD

**Issue by AhmedShabanElhdad95** [microblink/blinkid-android#300]
Before opening an issue, check that you are using the latest version of the BlinkID SDK.

Also, make sure your issue isn't on [the list of common problems.](https://github.com/BlinkID/blinkid-android#-faq-and-known-issues)
---

### Description
every time try to start scan get that error here
com.microblink.blinkid.licence.exception.InvalidLicenceKeyException: This entity is not allowed by currently active license!
<img width="1106" alt="Screenshot 2023-08-22 at 11 19 48" src="https://github.com/BlinkID/blinkid-android/assets/138496691/0e0dd00f-36f6-4e39-879b-c1c2675184cb">

Please try to provide steps to reproduce the issue, or minimal code sample. It will help us resolve the issue faster.

### Environment Details

**BlinkID version:**
com.microblink:blinkid:6.2.1@aar
**Device model:**
samsung  SM F925b
**Device Android version:**
12
**Device ABI (processor architecture, e.g. ARMv7):**

### Log file

Please enable logging by following instructions [here](https://github.com/BlinkID/blinkid-android#other-problems) and attach full log file.

 E  win=Window{58e3de4 u0 Splash Screen ae.gdi.identifyme EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=8 caller=com.android.server.wm.ActivityRecord.destroySurfaces:6283 com.android.server.wm.ActivityRecord.destroySurfaces:6264 com.android.server.wm.WindowState.onExitAnimationDone:6089 com.android.server.wm.WindowStateAnimator.onAnimationFinished:236 com.android.server.wm.WindowState.onAnimationFinished:6342 com.android.server.wm.WindowContainer$$ExternalSyntheticLambda0.onAnimationFinished:2 com.android.server.wm.SurfaceAnimator.lambda$getFinishedCallback$0$SurfaceAnimator:116 
2023-08-22 11:24:37.954 29967-29967 ViewRootIm...nActivity] ae.gdi.identifyme                    I  ViewPostIme pointer 0
2023-08-22 11:24:38.110 29967-29967 ViewRootIm...nActivity] ae.gdi.identifyme                    I  ViewPostIme pointer 1
2023-08-22 11:24:38.124 29967-29967 libc                    ae.gdi.identifyme                    E  Access denied finding property "ro.mediatek.platform"
2023-08-22 11:24:38.130 29967-29967 AndroidRuntime          ae.gdi.identifyme                    D  Shutting down VM
2023-08-22 11:24:38.130 29967-29967 AndroidRuntime          ae.gdi.identifyme                    E  FATAL EXCEPTION: main
                                                                                                    Process: ae.gdi.identifyme, PID: 29967
                                                                                                    com.microblink.blinkid.licence.exception.InvalidLicenceKeyException: This entity is not allowed by currently active license!
                                                                                                    	at com.microblink.blinkid.entities.recognizers.blinkid.generic.BlinkIdMultiSideRecognizer.nativeConstruct(Native Method)
                                                                                                    	at com.microblink.blinkid.entities.recognizers.blinkid.generic.BlinkIdMultiSideRecognizer.<init>(line:2)
                                                                                                    	at com.microblink.blinkid.activity.result.contract.TwoSideDocumentScan.createIntent(line:2)
                                                                                                    	at com.microblink.blinkid.activity.result.contract.TwoSideDocumentScan.createIntent(line:1)
                                                                                                    	at androidx.activity.ComponentActivity$2.onLaunch(ComponentActivity.java:216)
                                                                                                    	at androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:175)
                                                                                                    	at androidx.activity.result.ActivityResultLauncherKt.launch(ActivityResultLauncher.kt:25)
                                                                                                    	at androidx.activity.result.ActivityResultLauncherKt.launch$default(ActivityResultLauncher.kt:24)

### Additional information

If there is anything else that you think can help us resolve the issue, write it here.

**Comment by Brankacro** [comment]
Hello @AhmedShabanElhdad95 Thank you for reaching out. Since we received your request directly at support@microblink.com we suggest continuing the conversation directly via email. In case of any questions, feel free to reach out. Best regards.
