### ISSUE TITLE
UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__emutls_get_address"

### ISSUE THREAD

**Issue by shownstrong** [microblink/blinkid-android#328]
### Description
crash happens when MicroblinkSDK.setLicenseFile invoked.
Threre 2 cases.
case1: in a new empty project, crash log is InvalidLicenceKeyException: This license is invalid for application ID 'com.example.myapplication'
It's expected.

case2: in a complicated project, crash log is java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__emutls_get_address" 

Any ideas about case2 ?

### Environment Details

**BlinkID version:** 6.69.0

**Device model:Pixel 4
**Device Android version: Android 12

**Device ABI (processor architecture, e.g. ARMv7):**arm64-v8a, 

### Log file

java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__emutls_get_address" referenced by "/data/app/~~e1xSNzvmIELXuzj-fvXvxA==/com.xxx.xxx.xx-b9LWFquoZi2Z11C7NRuHgQ==/lib/arm64/libBlinkID.so"...
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1656)
                                                                                                    	at com.microblink.blinkid.secured.lIIllllIIl.IlIllIlIIl(line:5)
                                                                                                    	at com.microblink.blinkid.hardware.MicroblinkDeviceManager.<clinit>(line:35)
                                                                                                    	at com.microblink.blinkid.secured.lIIllllIIl.IlIllIlIIl(line:2)
                                                                                                    	at com.microblink.blinkid.secured.lIIllllIIl.llIIlIlIIl(line:1)
                                                                                                    	at com.microblink.blinkid.MicroblinkSDK.<clinit>(line:1)
                                                                                                    	at com.microblink.blinkid.MicroblinkSDK.setLicenseFile(Unknown Source:0)

### Additional information

**Comment by mparadina** [comment]
Hi @shownstrong

Can you confirm that the issue is present on a physical device?
Were you able to reproduce the issue on multiple devices?

To confirm, you were not able to reproduce the case 2 scenario with our [sample application](https://github.com/BlinkID/blinkid-android/tree/master/BlinkIDSample)?

Can you also tell me if you are using other 3rd libraries that contain the libc++ library?

**Comment by shownstrong** [comment]
Hi @mparadina 

1. yes, i can reproduce on a physical device, Pixel 4. 
2. I can't reproduce case2 with your sample application
3. Yes, our project is using other 3rd  libraries that contain the libc++ library

**Comment by mparadina** [comment]
Hi @shownstrong

Is this the full error log that you've displayed above, or is there some other information?
Can you share the full error log if possible?

**Comment by shownstrong** [comment]
@mparadina could you provide an email address. I will share the full log to you with the email

**Comment by shownstrong** [comment]
new version 6.10.0 is ok.
please close this issue

**Comment by mparadina** [comment]
Hi @shownstrong 
Thank you for the feedback.

Just to future readers of the issue, the caused exception might be connected with the` libc++` library if the SDK is used in a complicated project that also uses the same library for other 3rd party SDKs.

BlinkID v6.9, in its setup, is using the `libc++_shared.so` library, which could cause issues on your end if you're using other libraries that are using it.

However, with version 6.10, the SDK is using NDK r27 and has switched to statically linking `libc++`, which has most likely resolved the issue here.
